x-common-environment: &common-environment
  DEBUG:
  BUILDKITE:
  BUILDKITE_BRANCH:
  BUILDKITE_BUILD_CREATOR:
  BUILDKITE_BUILD_NUMBER:
  BUILDKITE_BUILD_URL:
  BUILDKITE_JOB_ID:
  BUILDKITE_LABEL:
  BUILDKITE_MESSAGE:
  BUILDKITE_PIPELINE_NAME:
  BUILDKITE_PIPELINE_SLUG:
  BUILDKITE_REPO:
  BUILDKITE_RETRY_COUNT:
  BUILDKITE_STEP_KEY:
  BUILDKITE_ANALYTICS_TOKEN:
  MAZE_BUGSNAG_API_KEY:
  MAZE_REPEATER_API_KEY:
  MAZE_ASPECTO_REPEATER_API_KEY:
  MAZE_NO_FAIL_FAST:

services:
  ci:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ci

  maze-runner-bb:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v9-cli
    environment:
      <<: *common-environment
      BITBAR_USERNAME:
      BITBAR_ACCESS_KEY:
    ports:
      - "9000-9499:9339"
      - "9000-9499:9340"
    volumes:
      - ./features/fixtures/ios/output:/app/build
      - ./features/:/app/features/
      - ./maze_output:/app/maze_output
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reports/:/app/reports/

  expo-maze-runner:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v9-cli
    environment:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_JOB_ID:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      BUILDKITE_ANALYTICS_TOKEN:
      MAZE_BUGSNAG_API_KEY:
      DEBUG:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      MAZE_NO_FAIL_FAST:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/build
      - ./features:/app/features
      - ./reports/:/app/reports/

  release:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.release
    environment:
      GITHUB_USER:
      GITHUB_ACCESS_TOKEN:
      RELEASE_BRANCH:
      RETRY_PUBLISH:
      VERSION:
    volumes:
      - ~/.gitconfig:/home/releaser/.gitconfig
      - ~/.npmrc:/home/releaser/.npmrc

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-js-maze-runner}
