version: '3.6'
services:
  ci:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ci

  expo-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo
      args:
        - BUILDKITE_BUILD_NUMBER
    environment:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_JOB_ID:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      MAZE_BUGSNAG_API_KEY:
      DEBUG:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/build

  release:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.release
    environment:
      GITHUB_USER:
      GITHUB_ACCESS_TOKEN:
      RELEASE_BRANCH:
      RETRY_PUBLISH:
      VERSION:
    volumes:
      - ~/.gitconfig:/home/releaser/.gitconfig
      - ~/.npmrc:/home/releaser/.npmrc

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-js-maze-runner}
