steps:
  #
  # License audit
  #
  - label: ':apple: Build expo IPA'

    timeout_in_minutes: 20
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths: build/output.ipa
    commands:
      - test/scripts/build-ios.sh

  - label: ':apple: Build expo IPA'

    timeout_in_minutes: 20
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths: build/output.ipa
    commands:
      - test/scripts/build-ios.sh

  - label: ':apple: Build expo IPA'

    timeout_in_minutes: 20
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths: build/output.ipa
    commands:
      - test/scripts/build-ios.sh

  - label: ':apple: Build expo IPA'

    timeout_in_minutes: 20
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths: build/output.ipa
    commands:
      - test/scripts/build-ios.sh

  - label: ':apple: Build expo IPA'

    timeout_in_minutes: 20
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths: build/output.ipa
    commands:
      - test/scripts/build-ios.sh

  - label: ':apple: Build expo IPA'

    timeout_in_minutes: 20
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths: build/output.ipa
    commands:
      - test/scripts/build-ios.sh

  - label: ':apple: Build expo IPA'

    timeout_in_minutes: 20
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths: build/output.ipa
    commands:
      - test/scripts/build-ios.sh

  - label: ':apple: Build expo IPA'

    timeout_in_minutes: 20
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths: build/output.ipa
    commands:
      - test/scripts/build-ios.sh