steps:
  #
  # License audit
  #
  - label: ':docker: Build expo maze runner image'
    key: "expo-maze-runner-image"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.9.0:
          build: expo-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
      - docker-compose#v3.9.0:
          push:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest

  - label: ':apple: Build expo IPA'
    key: "build-expo-ipa"
    timeout_in_minutes: 20
    agents:
      queue: "macos-13-arm"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
      DEVELOPER_DIR: "/Applications/Xcode-15.2.0.app"
      NODE_VERSION: "18"
    artifact_paths: build/output.ipa
    commands:
      - bundle install
      - features/scripts/build-ios.sh

  - label: ':runner: expo iOS 16'
    depends_on:
      - "build-expo-ipa"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.ipa"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.ipa
          - --farm=bs
          - --device=IOS_16
          - --a11y-locator
          - --retry=2
          - --order=random
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo iOS 14'
    depends_on:
      - "build-expo-ipa"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.ipa"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.ipa
          - --farm=bs
          - --device=IOS_14
          - --a11y-locator
          - --retry=2
          - --order=random
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
