#!/usr/bin/expect -f

set timeout -1
set api_key 645470b8c7f62177e1a723e26c9a48d7

# install
spawn npx bugsnag-expo-cli install

expect "@bugsnag/expo already appears to be installed, but is missing dependencies. Do you want to install them?"
send "y\r"

expect eof