# CI test image for unit/lint/type tests
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v6-cli as expo-maze-runner
COPY /test/features /app/test/features
COPY /test/scripts /app/test/scripts
WORKDIR /app/test
